import React, { useState, useEffect, useRef } from 'react';
import { 
  X, 
  Sparkles, 
  Send, 
  Copy, 
  Check, 
  ArrowRight,
  Key,
  Settings2,
  Cpu
} from 'lucide-react';
import { useApp } from '../../context/AppContext';

interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  codeSnippet?: string;
  actions?: { label: string; actionType: string; payload?: any }[];
  timestamp: string;
}

export const AICopilotDrawer: React.FC = () => {
  const { 
    isAICopilotOpen, 
    setIsAICopilotOpen, 
    copilotInitialPrompt,
    setCopilotInitialPrompt,
    setCurrentSection,
    setActiveSql,
    applyIndexOptimization,
    addToast,
    geminiConfig,
    setGeminiConfig,
    generateGeminiSQL
  } = useApp();

  const [input, setInput] = useState('');
  const [copiedCodeId, setCopiedCodeId] = useState<string | null>(null);
  const [isApiKeyModalOpen, setIsApiKeyModalOpen] = useState(false);
  const [apiKeyInput, setApiKeyInput] = useState(geminiConfig.apiKey);
  const [isTyping, setIsTyping] = useState(false);

  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'msg-init-1',
      sender: 'assistant',
      text: `Hello Arvind! I am **DataPilot Google Gemini Copilot**, your autonomous data analytics & engineering agent.
- **7 Sources** indexed (6 connected, 1 failed REST API)
- **3 Slow Queries** in PostgreSQL & BigQuery
- **2 Error Incidents** in Debug Center

How can I optimize your data pipeline today?`,
      timestamp: 'Just now',
      actions: [
        { label: '⚡ Diagnose Slow Dashboard (8.4s)', actionType: 'diag_slow' },
        { label: '🔌 Fix Stripe Webhook Error (429)', actionType: 'fix_stripe' },
        { label: '📊 Generate Sales MRR SQL Query', actionType: 'gen_sales_sql' }
      ]
    }
  ]);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (copilotInitialPrompt) {
      handleSendPrompt(copilotInitialPrompt);
      setCopilotInitialPrompt('');
    }
  }, [copilotInitialPrompt]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  const handleCopyCode = (code: string, id: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCodeId(id);
    addToast({ type: 'success', title: 'SQL Copied to Clipboard!' });
    setTimeout(() => setCopiedCodeId(null), 2000);
  };

  const handleAction = (actionType: string, payload?: any) => {
    switch (actionType) {
      case 'diag_slow':
        setCurrentSection('performance');
        setIsAICopilotOpen(false);
        break;
      case 'fix_stripe':
        setCurrentSection('debug');
        setIsAICopilotOpen(false);
        break;
      case 'gen_sales_sql':
        if (payload?.sql) {
          setActiveSql(payload.sql);
        } else {
          setActiveSql(`-- Monthly MRR Breakdown by Customer Tier
SELECT 
  DATE_TRUNC('month', created_at) AS cohort_month,
  plan_tier,
  COUNT(DISTINCT id) AS total_customers,
  SUM(mrr_usd) AS total_mrr
FROM public.customers
GROUP BY 1, 2
ORDER BY 1 DESC, 4 DESC;`);
        }
        setCurrentSection('sql');
        setIsAICopilotOpen(false);
        addToast({ type: 'info', title: 'SQL query loaded in IDE scratchpad.' });
        break;
      case 'apply_index':
        applyIndexOptimization('sq-1');
        break;
      default:
        break;
    }
  };

  const handleSendPrompt = async (promptText: string) => {
    if (!promptText.trim()) return;

    const userMsg: ChatMessage = {
      id: 'msg-' + Date.now(),
      sender: 'user',
      text: promptText,
      timestamp: 'Just now'
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput('');
    setIsTyping(true);

    const lower = promptText.toLowerCase();

    // Call Gemini AI or intelligent generator
    if (lower.includes('sql') || lower.includes('revenue') || lower.includes('query') || lower.includes('mrr') || lower.includes('churn') || lower.includes('show')) {
      const generatedSql = await generateGeminiSQL(promptText);
      setIsTyping(false);

      const assistantMsg: ChatMessage = {
        id: 'msg-' + (Date.now() + 1),
        sender: 'assistant',
        text: `Here is the optimized PostgreSQL query generated by **Google Gemini (${geminiConfig.model})** for your connected data mesh:`,
        codeSnippet: generatedSql,
        timestamp: 'Just now',
        actions: [
          { label: '🚀 Open in SQL IDE & Run', actionType: 'gen_sales_sql', payload: { sql: generatedSql } }
        ]
      };
      setMessages((prev) => [...prev, assistantMsg]);
      return;
    }

    // Performance diagnosis
    if (lower.includes('slow') || lower.includes('latency') || lower.includes('performance')) {
      setTimeout(() => {
        setIsTyping(false);
        const assistantMsg: ChatMessage = {
          id: 'msg-' + (Date.now() + 1),
          sender: 'assistant',
          text: `⚡ **Performance Diagnosis:**
- **Root Cause:** Query \`orders\` aggregation scans **4.28M rows sequentially** (8.42s latency).
- **Fix:** Create composite B-Tree index \`idx_orders_cust_date_amt\` on \`public.orders (customer_id, created_at) INCLUDE (total_amount)\`.
- **Expected Speedup:** 99.5% latency reduction (8,420ms ➔ **38ms**).`,
          codeSnippet: `CREATE INDEX CONCURRENTLY idx_orders_cust_date_amt 
ON public.orders (customer_id, created_at) 
INCLUDE (total_amount);`,
          timestamp: 'Just now',
          actions: [
            { label: '⚡ Apply Index Concurrently', actionType: 'apply_index' },
            { label: '🔍 View in Performance Center', actionType: 'diag_slow' }
          ]
        };
        setMessages((prev) => [...prev, assistantMsg]);
      }, 600);
      return;
    }

    // Default intelligent response
    setTimeout(() => {
      setIsTyping(false);
      const assistantMsg: ChatMessage = {
        id: 'msg-' + (Date.now() + 1),
        sender: 'assistant',
        text: `I analyzed your mesh catalog. All 7 data sources are mapped with active schema indexing across **PostgreSQL, Snowflake, and BigQuery**. 

Would you like me to write a query, check dbt model assertions, or generate automated Slack alert rules?`,
        timestamp: 'Just now',
        actions: [
          { label: '📊 Generate Revenue Query', actionType: 'gen_sales_sql' },
          { label: '⚡ Performance Center', actionType: 'diag_slow' }
        ]
      };
      setMessages((prev) => [...prev, assistantMsg]);
    }, 500);
  };

  const handleSaveApiKey = () => {
    setGeminiConfig({
      ...geminiConfig,
      apiKey: apiKeyInput,
      isLiveConnected: apiKeyInput.startsWith('AIza')
    });
    setIsApiKeyModalOpen(false);
    addToast({
      type: 'success',
      title: 'Gemini API Configured',
      message: apiKeyInput ? 'Live Google Gemini LLM active.' : 'Switched to built-in AI mode.'
    });
  };

  if (!isAICopilotOpen) return null;

  return (
    <div className="fixed inset-y-0 right-0 z-50 flex w-full sm:max-w-xl flex-col border-l-[3px] border-black bg-[#161b22] text-white shadow-[12px_0px_0px_#000000] font-mono text-xs animate-in slide-in-from-right duration-200">
      {/* Header */}
      <div className="flex items-center justify-between border-b-[3px] border-black bg-[#0d1117] p-3 sm:p-4 flex-shrink-0">
        <div className="flex items-center space-x-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded border-2 border-black bg-[#ffee00] text-black shadow-[2px_2px_0px_#000]">
            <Sparkles className="h-4 w-4 fill-black" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <h2 className="font-display text-sm font-black tracking-tight text-white uppercase">
                Google Gemini Copilot
              </h2>
              <span className="brutal-badge bg-[#00ff66] text-black text-[9px]">
                {geminiConfig.isLiveConnected ? 'LIVE API' : 'ONLINE'}
              </span>
            </div>
            <p className="text-[10px] text-slate-400">
              Model: {geminiConfig.model}
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-1.5">
          <button
            onClick={() => setIsApiKeyModalOpen(true)}
            className="brutal-badge bg-[#21262d] text-white cursor-pointer hover:bg-[#ffee00] hover:text-black p-1.5"
            title="Configure Gemini API Key"
          >
            <Key className="h-4 w-4" />
          </button>
          <button
            onClick={() => setIsAICopilotOpen(false)}
            className="brutal-badge bg-white text-black cursor-pointer hover:bg-[#ffee00] p-1.5"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Chat Messages */}
      <div className="flex-1 overflow-y-auto p-3 sm:p-4 space-y-4">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex flex-col ${msg.sender === 'user' ? 'items-end' : 'items-start'}`}
          >
            <div
              className={`max-w-[90%] sm:max-w-[85%] rounded border-2 border-black p-3.5 shadow-[3px_3px_0px_#000] ${
                msg.sender === 'user'
                  ? 'bg-[#00f0ff] text-black font-bold'
                  : 'bg-[#0d1117] text-slate-100'
              }`}
            >
              <div className="whitespace-pre-wrap leading-relaxed font-sans text-xs">
                {msg.text}
              </div>

              {/* Code Snippet */}
              {msg.codeSnippet && (
                <div className="mt-3 rounded border-2 border-black bg-[#161b22] p-3 text-[#00f0ff] font-mono text-[11px]">
                  <div className="flex items-center justify-between border-b border-black pb-1.5 mb-2">
                    <span className="text-[9px] text-[#ffee00] font-black uppercase">// POSTGRESQL CODE</span>
                    <button
                      onClick={() => handleCopyCode(msg.codeSnippet!, msg.id)}
                      className="flex items-center text-[10px] text-slate-300 hover:text-white font-bold"
                    >
                      {copiedCodeId === msg.id ? (
                        <>
                          <Check className="h-3 w-3 mr-1 text-[#00ff66]" />
                          <span className="text-[#00ff66]">COPIED</span>
                        </>
                      ) : (
                        <>
                          <Copy className="h-3 w-3 mr-1" />
                          <span>COPY</span>
                        </>
                      )}
                    </button>
                  </div>
                  <pre className="overflow-x-auto">{msg.codeSnippet}</pre>
                </div>
              )}

              {/* Action Buttons */}
              {msg.actions && msg.actions.length > 0 && (
                <div className="mt-3 pt-2.5 border-t border-black flex flex-wrap gap-1.5">
                  {msg.actions.map((act, i) => (
                    <button
                      key={i}
                      onClick={() => handleAction(act.actionType, act.payload)}
                      className="brutal-btn bg-white text-black hover:bg-[#ffee00] px-2.5 py-1.5 text-[10px] font-black min-h-[32px]"
                    >
                      <span>{act.label}</span>
                      <ArrowRight className="h-3 w-3 ml-1" />
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}

        {isTyping && (
          <div className="flex items-center space-x-2 brutal-badge bg-[#0d1117] text-[#00ff66] w-fit">
            <Cpu className="h-3.5 w-3.5 animate-spin" />
            <span>Gemini AI is generating query...</span>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Quick Prompts */}
      <div className="border-t-[3px] border-black bg-[#0d1117] px-3 sm:px-4 py-2 flex-shrink-0">
        <div className="text-[9px] font-black text-[#ffee00] uppercase tracking-wider mb-1.5">
          // QUICK PROMPTS
        </div>
        <div className="flex flex-wrap gap-1.5">
          <button
            onClick={() => handleSendPrompt('Why is my dashboard slow?')}
            className="brutal-btn bg-[#21262d] text-white hover:bg-[#ffee00] hover:text-black px-2 py-1.5 text-[10px] min-h-[32px]"
          >
            ⚡ Why is dashboard slow?
          </button>
          <button
            onClick={() => handleSendPrompt('Show monthly revenue for the last 12 months.')}
            className="brutal-btn bg-[#21262d] text-white hover:bg-[#ffee00] hover:text-black px-2 py-1.5 text-[10px] min-h-[32px]"
          >
            📊 Monthly revenue SQL
          </button>
        </div>
      </div>

      {/* Chat Input Bar */}
      <div className="border-t-[3px] border-black bg-[#0d1117] p-3 sm:p-3.5 flex-shrink-0">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSendPrompt(input);
          }}
          className="flex items-center gap-2"
        >
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask Gemini anything about your database schemas..."
            className="w-full brutal-box px-3 py-2 text-xs text-white placeholder-slate-500 outline-none bg-[#0d1117] min-h-[40px]"
          />
          <button
            type="submit"
            disabled={!input.trim()}
            className="brutal-btn brutal-btn-yellow px-4 py-2 text-xs font-black disabled:opacity-40 min-h-[40px] min-w-[44px]"
          >
            <Send className="h-4 w-4" />
          </button>
        </form>
      </div>

      {/* Gemini API Key Configuration Modal */}
      {isApiKeyModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
          <div className="w-full max-w-md brutal-panel p-5 bg-[#161b22] border-[3px] border-black shadow-[10px_10px_0px_#000] space-y-4">
            <div className="flex items-center justify-between border-b-2 border-black pb-2">
              <span className="font-display text-base font-black text-white uppercase">GOOGLE GEMINI API KEY</span>
              <button onClick={() => setIsApiKeyModalOpen(false)} className="brutal-badge bg-white text-black">ESC</button>
            </div>

            <div className="space-y-3">
              <p className="text-xs text-slate-300">
                Enter your Google Gemini API Key to enable live streaming LLM query generation directly on your database schemas.
              </p>

              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">API Key</label>
                <input
                  type="password"
                  value={apiKeyInput}
                  onChange={(e) => setApiKeyInput(e.target.value)}
                  placeholder="AIzaSy..."
                  className="w-full brutal-box px-3 py-2 text-white bg-[#0d1117] outline-none"
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">Model</label>
                <select
                  value={geminiConfig.model}
                  onChange={(e) => setGeminiConfig({ ...geminiConfig, model: e.target.value as any })}
                  className="w-full brutal-box px-2 py-1.5 text-white bg-[#0d1117]"
                >
                  <option value="gemini-2.0-flash">gemini-2.0-flash (Fast & Accurate)</option>
                  <option value="gemini-1.5-pro">gemini-1.5-pro (Complex Reasoning)</option>
                  <option value="gemini-1.5-flash">gemini-1.5-flash</option>
                </select>
              </div>
            </div>

            <div className="flex justify-end space-x-2 pt-3 border-t-2 border-black">
              <button onClick={() => setIsApiKeyModalOpen(false)} className="brutal-btn bg-[#21262d] text-white px-3 py-1.5">CANCEL</button>
              <button onClick={handleSaveApiKey} className="brutal-btn brutal-btn-yellow px-4 py-1.5 font-black">SAVE KEY</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
